version: '3.9'
services: 
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db
  db:
    image: mysql:8
    environment: 
      MYSQL_DATABASE: ambassador
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./storage/dbdata:/var/lib/mysql
